/**
 * The game in progress, so closing the playtester does not concede it.
 *
 * Goldfishing is a conversation with the deck: you play five turns, notice the
 * curve stalls, go and look at what you have, and come back. Closing the mat
 * dealt a fresh seven and threw the board away, which made "go and look"
 * expensive enough that the honest move was not to look.
 *
 * In memory rather than sessionStorage, like the deck view cache: a board is a
 * few hundred whole card records and it is only worth anything while the tab
 * is open.
 */

import type { Card } from './api'
import type { DeckCard } from './deckModel'

export type Zone = 'library' | 'hand' | 'battlefield' | 'graveyard' | 'exile' | 'command'

export interface Instance {
  iid: string
  card: Card
  zone: Zone
  tapped: boolean
  /** Position on the playmat, as a fraction of its size. Only meaningful on
   *  the battlefield; kept as fractions so the board survives a resize. */
  x: number
  y: number
}

/**
 * The die, as it sits on the mat.
 *
 * Position is fractional like a card's, but of the *free* space rather than
 * the mat: 1 means "right edge touching the far side", not "off the board".
 * That makes clamping a plain 0..1 and keeps the die fully visible at any
 * window size.
 */
export type DieKind = 'd6' | 'd20'

export interface DieState {
  id: string
  kind: DieKind
  x: number
  y: number
  value: number
  /** Counting rather than rolling: clicks step the face instead of it being
   *  something you throw. */
  counting: boolean
  /** Still in its tray.
   *
   * A die at home ignores its stored coordinates entirely and is placed from
   * the tray element's measured position. Flexbox decides where that tray
   * lands, so converting it to a fraction of the mat and back put every
   * spawned die a few pixels outside the outline it was supposed to be
   * sitting in -- including the very first one, which was placed from a
   * guessed constant before the measurement had even run. Measure once, place
   * exactly, and only convert to a fraction on the way out. */
  home: boolean
}

/** Fractional position of something on the mat. */
export interface Spot { x: number; y: number }

/** Enough to track a board state, few enough that the mat stays a board. */
export const MAX_DICE = 10

/** Rendered size of a die, matching `.pt-die`. Shared because the fractional
 *  coordinates are of the mat *less* this, and both ends must agree. */
export const DIE_PX = 46

/** How near its tray a die must be dropped to count as put away, in px. */
export const TRAY_SNAP = 40

export const DIE_SIDES: Record<DieKind, number> = { d6: 6, d20: 20 }

let dieCounter = 0

export function makeDie(kind: DieKind): DieState {
  dieCounter += 1
  return {
    id: `die${dieCounter}`, kind, x: 0, y: 0,
    value: DIE_SIDES[kind], counting: false, home: true,
  }
}

export interface SavedGame {
  cards: Instance[]
  turn: number
  life: number
  mulligans: number
  log: string[]
  /* The dice and the coin are deliberately absent.
   *
   * They are what is on the table right now, not what the game is: a board
   * mid-combat is worth coming back to, a scatter of dice from three turns
   * ago is clutter you would have swept up anyway. Leaving the mat puts them
   * back in their trays. */
  /** What the deck looked like when this game was dealt. */
  signature: string
}

const games = new Map<string, SavedGame>()

/** Only a couple of decks are ever in flight; this stops it growing forever. */
const LIMIT = 3

/**
 * What the deck consists of, order-independent.
 *
 * A resumed game has to be a game of *this* deck. Card uids are regenerated by
 * every re-analysis, so they cannot be compared; the cards, their counts and
 * their sections can, and those are exactly what would make a saved board
 * wrong.
 */
export function deckSignature(deck: DeckCard[]): string {
  return deck
    .map((entry) => `${entry.card.oracle_id}:${entry.quantity}:${entry.section}`)
    .sort()
    .join('|')
}

export function rememberGame(key: string, game: SavedGame) {
  games.delete(key)
  games.set(key, game)
  while (games.size > LIMIT) {
    const oldest = games.keys().next().value
    if (oldest === undefined) break
    games.delete(oldest)
  }
}

/** The saved game for this deck, or undefined if there is none — or if the
 *  deck has been edited since, in which case resuming would be a lie. */
export function recallGame(key: string, signature: string): SavedGame | undefined {
  const game = games.get(key)
  return game && game.signature === signature ? game : undefined
}

export function forgetGame(key: string) {
  games.delete(key)
}
