/**
 * The game in progress, so closing the playtester does not concede it.
 *
 * Goldfishing is a conversation with the deck: you play five turns, notice the
 * curve stalls, go and look at what you have, and come back. Closing the mat
 * dealt a fresh seven and threw the board away, which made "go and look"
 * expensive enough that the honest move was not to look.
 *
 * In memory rather than sessionStorage, like the deck view cache: a board is a
 * few hundred whole card records and it is only worth anything while the tab
 * is open.
 */

import type { Card } from './api'
import type { DeckCard } from './deckModel'

export type Zone = 'library' | 'hand' | 'battlefield' | 'graveyard' | 'exile' | 'command'

export interface Instance {
  iid: string
  card: Card
  zone: Zone
  tapped: boolean
  /** Position on the playmat, as a fraction of its size. Only meaningful on
   *  the battlefield; kept as fractions so the board survives a resize. */
  x: number
  y: number
}

/**
 * The die, as it sits on the mat.
 *
 * Position is fractional like a card's, but of the *free* space rather than
 * the mat: 1 means "right edge touching the far side", not "off the board".
 * That makes clamping a plain 0..1 and keeps the die fully visible at any
 * window size.
 */
export interface DieState {
  id: string
  x: number
  y: number
  value: number
  /** Counting rather than rolling: clicks step the face instead of it being
   *  something you throw. */
  counting: boolean
  /** The one still sitting in the tray. Moving it away spawns its
   *  replacement, so there is always exactly one die to reach for. */
  home: boolean
}

/** Fractional position of something on the mat. */
export interface Spot { x: number; y: number }

/** Where the tray sits before it has been measured. The real position comes
 *  from the tray element itself, which flexbox lays out inside the tool
 *  column and so cannot be written down as a constant. */
export const DIE_HOME: Spot = { x: 0.96, y: 0.62 }

/** Enough to track a board state, few enough that the mat stays a board. */
export const MAX_DICE = 8

/** Rendered size of a die, matching `.pt-die`. Shared because the fractional
 *  coordinates are of the mat *less* this, and both ends must agree. */
export const DIE_PX = 46

let dieCounter = 0

export function makeDie(home: boolean, at: Spot = DIE_HOME): DieState {
  dieCounter += 1
  return { id: `d${dieCounter}`, x: at.x, y: at.y, value: 6, counting: false, home }
}

/** Whether a die has been put back in the tray. Generous, and wider than it is
 *  tall because the fractions are of the mat's own dimensions, so an equal
 *  fraction is a much longer distance across than down. */
export function inTray(die: DieState, home: Spot): boolean {
  return Math.abs(die.x - home.x) < 0.035 && Math.abs(die.y - home.y) < 0.09
}

export interface SavedGame {
  cards: Instance[]
  turn: number
  life: number
  mulligans: number
  log: string[]
  /** Every die on the mat, where it came to rest and what it showed. */
  dice: DieState[]
  /** The two fixed tools beside the tray. */
  d20: number
  coin: 'heads' | 'tails'
  /** What the deck looked like when this game was dealt. */
  signature: string
}

const games = new Map<string, SavedGame>()

/** Only a couple of decks are ever in flight; this stops it growing forever. */
const LIMIT = 3

/**
 * What the deck consists of, order-independent.
 *
 * A resumed game has to be a game of *this* deck. Card uids are regenerated by
 * every re-analysis, so they cannot be compared; the cards, their counts and
 * their sections can, and those are exactly what would make a saved board
 * wrong.
 */
export function deckSignature(deck: DeckCard[]): string {
  return deck
    .map((entry) => `${entry.card.oracle_id}:${entry.quantity}:${entry.section}`)
    .sort()
    .join('|')
}

export function rememberGame(key: string, game: SavedGame) {
  games.delete(key)
  games.set(key, game)
  while (games.size > LIMIT) {
    const oldest = games.keys().next().value
    if (oldest === undefined) break
    games.delete(oldest)
  }
}

/** The saved game for this deck, or undefined if there is none — or if the
 *  deck has been edited since, in which case resuming would be a lie. */
export function recallGame(key: string, signature: string): SavedGame | undefined {
  const game = games.get(key)
  return game && game.signature === signature ? game : undefined
}

export function forgetGame(key: string) {
  games.delete(key)
}
