# PyInstaller spec for the distributable build.
#
# onedir, not onefile. A onefile build unpacks ~60MB to a temp directory on
# every launch, which is slow and confuses antivirus; a folder is also what
# Inno Setup wants to lay down. The cost is that the payload is visible beside
# the executable, which for a free tool is not a cost.
#
# Build from the repo root:
#     server\.venv\Scripts\pyinstaller packaging\insight-engine.spec --noconfirm

from pathlib import Path

# SPECPATH is the directory holding this file; the repo root is its parent.
ROOT = Path(SPECPATH).parent          # noqa: F821 - injected by PyInstaller
SERVER = ROOT / "server"

datas = [
    # The built interface. Without this the server has nothing to serve, so a
    # missing `web/dist` should fail the build rather than ship a blank app.
    (str(ROOT / "web" / "dist"), "web/dist"),
    # The sample deck a fresh install is seeded with.
    (str(SERVER / "app" / "seed"), "app/seed"),
    # A small starter mirror, so the app works the moment it is installed
    # rather than after a 175MB download -- and does not open on "the card
    # database did not finish building" when that download fails. Built by
    # packaging/make-seed.py; the full mirror is fetched in the background.
    (str(ROOT / "packaging" / "seed-mirror.sqlite3"), "."),
]

if not (ROOT / "packaging" / "seed-mirror.sqlite3").exists():
    raise SystemExit(
        "packaging/seed-mirror.sqlite3 is missing. Build it with: "
        r"server\.venv\Scripts\python packaging\make-seed.py"
    )

if not (ROOT / "web" / "dist" / "index.html").exists():
    raise SystemExit(
        "web/dist is missing. Run `npm --prefix web run build` before packaging."
    )

hiddenimports = [
    # uvicorn resolves these by name at runtime, so static analysis misses them.
    "uvicorn.logging",
    "uvicorn.loops.auto",
    "uvicorn.loops.asyncio",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.http.h11_impl",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.lifespan.on",
    # Pulled in through pydantic-settings' dotenv support.
    "dotenv",
    # The tray. pystray picks its Windows backend at import time, so the
    # concrete module is invisible to static analysis and the frozen build
    # would start, find no backend, and quietly run without an icon.
    "pystray",
    "pystray._win32",
    "PIL.Image",
    "PIL.ImageDraw",
]

a = Analysis(                          # noqa: F821
    [str(ROOT / "packaging" / "entry.py")],
    # So `import app.…` resolves the same way it does from a source checkout.
    pathex=[str(SERVER)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    # Test-only, and pulling them in adds weight for nothing.
    excludes=["pytest", "pytest_asyncio", "_pytest"],
    noarchive=False,
)

pyz = PYZ(a.pure)                      # noqa: F821

exe = EXE(                             # noqa: F821
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="InsightEngine",
    debug=False,
    strip=False,
    upx=False,
    # Windowed. A console cannot be hidden from inside the process on Windows
    # 11: the window we own is a ConPTY stub that is already invisible, and the
    # one on screen belongs to conhost.exe or WindowsTerminal.exe. So there is
    # never one. Progress goes to the tray tooltip, the running account to a log
    # beside the database, and failures to a message box.
    console=False,
    # Regenerated by build-release.ps1 from app/icon.py, so the executable,
    # the installer and the tray all wear the same mark.
    icon=str(ROOT / "packaging" / "insight-engine.ico"),
)

coll = COLLECT(                        # noqa: F821
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="InsightEngine",
)
